In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(Path('covid_deaths.csv'))
df

,REGION,Key,Area,CENSUS_2010_TOTAL_POPULATION,CENSUS_2010_STATE_DENSITY,CENSUS_2010_RANK,2020_STATE_DENSITY,STATE_LAND_AREA,Major_City_CBSA_Title,CBSA Code,...,Census_Population_Over_60,Census_Population_Over_60_Employment_Rate,Census_Total_Population_Over_16_Estimate,Census_Total_Workers_Over_16_Estimate,COMMUTE_Census_Worker_Drive_To_Work_Rate,COMMUTE_Census_Worker_Carpool_To_Work_Rate,COMMUTE_Census_Worker_Public_Transportation_Rate,COMMUTE_Census_Worker_Walk_Rate,COMMUTE_Census_Worker_Taxicab_Motorcycle_Bicycle_Other_Rate,COMMUTE_Census_Work_At_Home_Rate
0,Alabama,1,South,4779736,94.4,29,97,50645,"Mobile, AL Metro Area",33660,...,1149135,0.24,3854015,2055708,0.86,0.08,0.00,0.01,0.01,0.03
1,Alaska,2,West,710231,1.2,52,1,570641,"Anchorage, AK Metro Area",11260,...,134012,0.35,548676,337552,0.68,0.12,0.01,0.08,0.06,0.05
2,Arizona,3,West,6392017,56.3,35,65,113594,"Phoenix-Mesa-Glendale, AZ Metro Area",38060,...,1695429,0.24,5608516,3155343,0.76,0.11,0.02,0.02,0.03,0.07
3,Arkansas,4,South,2915918,56.0,36,58,52035,"Fayetteville-Springdale-Rogers, AR-MO Metro Area",22220,...,695572,0.25,2336993,1297409,0.83,0.10,0.00,0.02,0.01,0.04
4,California,5,West,37253956,239.1,13,256,155779,"San Francisco-Oakland-Fremont, CA Metro Area",41860,...,7963713,0.29,31085639,18399115,0.74,0.10,0.05,0.03,0.03,0.06
5,Colorado,6,West,5029196,48.5,39,56,103642,"Denver-Aurora-Broomfield, CO Metro Area",19740,...,1156858,0.32,4479249,2930149,0.75,0.09,0.03,0.03,0.02,0.09
6,Connecticut,7,Northeast,3574097,738.1,6,736,4842,"Bridgeport-Stamford-Norwalk, CT Metro Area",14860,...,865770,0.34,2884868,1785761,0.78,0.08,0.05,0.03,0.01,0.06
7,Delaware,8,South,897934,460.8,8,504,1949,"Dover, DE Metro Area",20100,...,248295,0.28,773385,449293,0.80,0.09,0.02,0.02,0.01,0.06
8,District of Columbia,9,South,601723,9856.5,1,11815,61,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",47900,...,118779,0.31,576927,375487,0.34,0.05,0.35,0.13,0.07,0.06
9,Florida,10,South,18801310,350.6,10,410,53625,"Miami-Fort Lauderdale-Pompano Beach, FL Metro ...",33100,...,5765648,0.24,17262966,9557108,0.79,0.09,0.02,0.01,0.02,0.06
10,Georgia,11,South,9687653,168.4,20,288,40861,"Atlanta-Sandy Springs-Marietta, GA Metro Area",12060,...,2070692,0.28,8128931,4847726,0.79,0.09,0.02,0.01,0.02,0.06
11,Hawaii,12,West,1360301,211.8,15,220,6423,"Honolulu, HI Metro Area",26180,...,355338,0.32,1096009,666501,0.67,0.15,0.06,0.03,0.03,0.06
12,Idaho,13,West,1567582,19.0,46,22,82643,"Pocatello, ID Metro Area",38540,...,382826,0.26,1337554,791148,0.80,0.09,0.01,0.03,0.02,0.06
13,Illinois,14,Midwest,12830632,231.1,14,228,55519,"Chicago-Joliet-Naperville, IL-IN-WI Metro Area",16980,...,2804799,0.29,10040920,6174906,0.73,0.08,0.09,0.03,0.02,0.05
14,Indiana,15,Midwest,6483802,181.0,18,188,35826,"Lafayette, IN Metro Area",29140,...,1477824,0.29,5205600,3171334,0.83,0.09,0.01,0.02,0.02,0.04
15,Iowa,16,Midwest,3046355,54.5,38,57,55857,"Iowa City, IA Metro Area",26980,...,743615,0.32,2464341,1587362,0.82,0.08,0.01,0.03,0.01,0.05
16,Kansas,17,Midwest,2853118,34.9,42,36,81759,"Lawrence, KS Metro Area",29940,...,645949,0.31,2229203,1418803,0.82,0.09,0.01,0.02,0.01,0.05
17,Kentucky,18,South,4339367,109.9,24,114,39486,"Lexington-Fayette, KY Metro Area",30460,...,1026703,0.24,3492675,1952946,0.83,0.09,0.01,0.02,0.01,0.04
18,Louisiana,19,South,4533372,104.9,26,108,43204,"New Orleans-Metairie-Kenner, LA Metro Area",35380,...,1019862,0.26,3579169,1978312,0.83,0.09,0.01,0.02,0.02,0.03
19,Maine,20,Northeast,1328361,43.1,40,44,30843,"Lewiston-Auburn, ME Metro Area",30340,...,384322,0.30,1105382,664351,0.78,0.10,0.01,0.04,0.02,0.06
20,Maryland,21,South,5773552,594.8,7,627,9707,"Baltimore-Towson, MD Metro Area",12580,...,1324920,0.33,4754654,3034807,0.74,0.09,0.08,0.02,0.02,0.05
21,Massachusetts,22,Northeast,6547629,839.4,5,894,7800,"Boston-Cambridge-Quincy, MA-NH Metro Area",14460,...,1588116,0.33,5633413,3554798,0.70,0.07,0.10,0.05,0.02,0.05
22,Michigan,23,Midwest,9883640,174.8,19,178,56539,"Detroit-Warren-Livonia, MI Metro Area",19820,...,2421416,0.25,7986376,4611616,0.82,0.09,0.01,0.02,0.01,0.04
23,Minnesota,24,Midwest,5303925,66.6,33,72,79627,"Minneapolis-St. Paul-Bloomington, MN-WI Metro ...",33460,...,1243961,0.31,4395381,2920543,0.78,0.08,0.04,0.03,0.02,0.06
24,Mississippi,25,South,2967297,63.2,34,64,46923,"Jackson, MS Metro Area",27140,...,667073,0.24,2296728,1207063,0.86,0.09,0.00,0.01,0.01,0.03
25,Missouri,26,Midwest,5988927,87.1,30,90,68742,"Lansing-East Lansing, MI Metro Area",29620,...,1448367,0.27,4797181,2873163,0.82,0.09,0.01,0.02,0.01,0.05
26,Montana,27,West,989415,6.8,50,7,145546,"Kansas City, MO-KS Metro Area",28140,...,279971,0.31,843546,511597,0.75,0.09,0.01,0.06,0.02,0.07
27,Nebraska,28,Midwest,1826341,23.8,45,25,76824,"Lincoln, NE Metro Area",30700,...,423109,0.35,1477589,980815,0.82,0.09,0.01,0.03,0.01,0.05
28,Nevada,29,West,2700551,24.6,44,29,109781,"Las Vegas-Paradise, NV Metro Area",29820,...,661507,0.27,2385543,1418382,0.78,0.11,0.03,0.02,0.02,0.04
29,New Hampshire,30,Northeast,1316470,147.0,23,153,8953,"Manchester-Nashua, NH Metro Area",31700,...,346662,0.34,1112869,712442,0.81,0.07,0.01,0.03,0.02,0.07
30,New Jersey,31,Northeast,8791894,1195.5,2,1215,7354,"Trenton-Ewing, NJ Metro Area",45940,...,2022272,0.33,7080172,4386693,0.71,0.08,0.12,0.03,0.02,0.05
31,New Mexico,32,West,2059179,17.0,47,17,121298,"Albuquerque, NM Metro Area",10740,...,504653,0.24,1639138,865888,0.79,0.11,0.01,0.02,0.02,0.05
32,New York,33,Northeast,19378102,411.2,9,413,47126,"New York-Northern New Jersey-Long Island, NY-N...",35620,...,4480458,0.29,15709161,9287627,0.53,0.06,0.28,0.06,0.02,0.05
33,North Carolina,34,South,9535483,196.1,17,218,148618,"Charlotte-Gastonia-Rock Hill, NC-SC Metro Area",16740,...,2353499,0.27,8154786,4768759,0.81,0.09,0.01,0.02,0.01,0.06
34,North Dakota,35,Midwest,672591,9.7,49,11,69001,"Fargo, ND-MN Metro Area",22020,...,162220,0.32,585782,392429,0.82,0.09,0.01,0.03,0.01,0.04
35,Ohio,36,Midwest,11536504,282.3,12,288,40861,"Cleveland-Elyria-Mentor, OH Metro Area",17460,...,2792679,0.28,9237632,5515839,0.82,0.08,0.02,0.02,0.01,0.04
36,Oklahoma,37,South,3751351,54.7,37,58,68595,"Oklahoma City, OK Metro Area",36420,...,857599,0.28,3008712,1758388,0.83,0.10,0.00,0.02,0.01,0.04
37,Oregon,38,West,3831074,39.9,41,45,95988,"Portland-Vancouver-Hillsboro, OR-WA Metro Area",38900,...,1016180,0.25,3379241,1992019,0.72,0.10,0.04,0.04,0.03,0.08
38,Pennsylvania,39,Northeast,12702379,283.9,11,287,44743,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",37980,...,3227151,0.29,10271420,6129917,0.76,0.09,0.06,0.04,0.02,0.05
39,Rhode Island,40,Northeast,1052567,1018.1,4,1021,1034,"Providence-New Bedford-Fall River, RI-MA Metro...",39300,...,257992,0.31,865601,515707,0.82,0.08,0.02,0.03,0.01,0.04
40,South Carolina,41,South,4625364,153.9,22,173,30061,"Charleston-North Charleston-Summerville, SC Me...",16700,...,1228275,0.25,4012850,2268973,0.82,0.10,0.01,0.01,0.02,0.05
41,South Dakota,42,Midwest,814180,10.7,48,12,75811,"Sioux Falls, SD Metro Area",43620,...,205307,0.35,673526,445146,0.81,0.09,0.00,0.03,0.01,0.06
42,Tennessee,43,South,6346105,153.9,21,167,41235,"Memphis, TN-MS-AR Metro Area",32820,...,1550510,0.27,5330967,3076837,0.83,0.09,0.01,0.01,0.01,0.05
43,Texas,44,South,25145561,96.3,28,113,261232,"Laredo, TX Metro Area",29700,...,5139025,0.30,21663694,13256665,0.81,0.10,0.01,0.01,0.02,0.05
44,Utah,45,West,2763885,33.6,43,40,82170,"Salt Lake City, UT Metro Area",41620,...,499149,0.30,2305534,1510473,0.76,0.11,0.02,0.02,0.02,0.07
45,Vermont,46,Northeast,625741,67.9,32,68,9217,"Burlington-South Burlington, VT Metro Area",15540,...,172909,0.36,519162,323581,0.75,0.09,0.01,0.05,0.02,0.08
46,Virginia,47,South,8001024,202.6,16,218,39490,"Richmond, VA Metro Area",40060,...,1847250,0.31,6642133,4103126,0.77,0.09,0.05,0.02,0.02,0.06
47,Washington,48,West,6724540,101.2,27,117,66456,"Seattle-Tacoma-Bellevue, WA Metro Area",42660,...,1636420,0.28,5946027,3609979,0.71,0.10,0.07,0.04,0.02,0.07
48,West Virginia,49,South,1852994,77.1,31,74,24038,"Morgantown, WV Metro Area",34060,...,492418,0.21,1459045,726374,0.83,0.09,0.01,0.03,0.01,0.03
49,Wisconsin,50,Midwest,5686986,105.0,25,108,54158,"Milwaukee-Waukesha-West Allis, WI Metro Area",33340,...,1391738,0.29,4621479,2952361,0.82,0.08,0.02,0.03,0.02,0.05
50,Wyoming,51,West,563626,5.8,51,6,97093,"Casper, WY Metro Area",16220,...,137988,0.32,449840,280862,0.76,0.10,0.01,0.04,0.02,0.06

In [19]:
df.drop(['Key','CENSUS_2010_RANK', '2020_STATE_DENSITY','STATE_LAND_AREA', 'CBSA Code', 'Census_Population_Over_60','Census_Population_Over_60_Employment_Rate'], axis = 1, inplace = True)

In [20]:
df.head()

,REGION,Area,CENSUS_2010_TOTAL_POPULATION,CENSUS_2010_STATE_DENSITY,Major_City_CBSA_Title,CBSA_Major_City_Population_2010,CBSA_Major_City_max_weighted_density,CBSA_Major_City_mean_pop_density,Covid_Positive,Covid_Negative,...,BRFSS_55_64_Other_Cancer_Rate,BRFSS_65_plus_Other_Cancer_Rate,Census_Total_Population_Over_16_Estimate,Census_Total_Workers_Over_16_Estimate,COMMUTE_Census_Worker_Drive_To_Work_Rate,COMMUTE_Census_Worker_Carpool_To_Work_Rate,COMMUTE_Census_Worker_Public_Transportation_Rate,COMMUTE_Census_Worker_Walk_Rate,COMMUTE_Census_Worker_Taxicab_Motorcycle_Bicycle_Other_Rate,COMMUTE_Census_Work_At_Home_Rate
0,Alabama,South,4779736,94.4,"Mobile, AL Metro Area",412992,1659.3,1056.681818,981,6298,...,0.008910,0.015471,3854015,2055708,0.86,0.08,0.00,0.01,0.01,0.03
1,Alaska,West,710231,1.2,"Anchorage, AK Metro Area",380821,3006.9,2035.000000,119,3594,...,0.004340,0.010168,548676,337552,0.68,0.12,0.01,0.08,0.06,0.05
2,Arizona,West,6392017,56.3,"Phoenix-Mesa-Glendale, AZ Metro Area",4192887,4394.9,1838.788889,1289,18082,...,0.006308,0.013680,5608516,3155343,0.76,0.11,0.02,0.02,0.03,0.07
3,Arkansas,South,2915918,56.0,"Fayetteville-Springdale-Rogers, AR-MO Metro Area",463204,1114.8,931.666667,523,5959,...,0.008787,0.016704,2336993,1297409,0.83,0.10,0.00,0.02,0.01,0.04
4,California,West,37253956,239.1,"San Francisco-Oakland-Fremont, CA Metro Area",4335391,12144.9,4684.784615,7482,21772,...,0.004582,0.009686,31085639,18399115,0.74,0.10,0.05,0.03,0.03,0.06

In [21]:
df.columns

Index(['REGION', 'Area', 'CENSUS_2010_TOTAL_POPULATION',
       'CENSUS_2010_STATE_DENSITY', 'Major_City_CBSA_Title',
       'CBSA_Major_City_Population_2010',
       'CBSA_Major_City_max_weighted_density',
       'CBSA_Major_City_mean_pop_density', 'Covid_Positive', 'Covid_Negative',
       'Covid_Pending', 'Covid_Hospitalized', 'Covid_Death', 'Covid_Total',
       'Last_Covid_Update', 'FLUVIEW_TOTAL_INFLUENZA_DEATHS_Season_2018',
       'FLUVIEW_TOTAL_PNEUMONIA_DEATHS_Season_2018',
       'Kaiser_Total_Hospital_Beds', 'Kaiser_Beds_per_1000_Population',
       'Kaiser_Total_CHCs', 'Kaiser_CHC_Service_Delivery_Sites',
       'BRFSS_Asthma_Prevalance', 'Fluview_US_FLU_Hospitalization_Rate_Asthma',
       'BRFSS_Age_55_64_Asthma_Rate', 'BRFSS_Age_65_plus_Asthma_Rate',
       'BRFSS_COPD_Prevalance',
       'Fluview_US_FLU_Hospitalization_Rate_Lung_Disease',
       'BRFSS_Age_55_64_COPD_Rate', 'BRFSS_Age_65_plus_COPD_Rate',
       'BRFSS_Heart_Disease_Prevalance',
       'Fluview_US_FLU_Hospitalization_Rate_Heart_Disease',
       'BRFSS_Age_55_64_Heart_Disease_Rate',
       'BRFSS_Age_65_plus_Heart_Disease_Rate',
       'BRFSS_2017_High_Cholestoral_Prevalance',
       'BRFSS_2017_High_Blood_Pressure_Prevalance',
       'BRFSS_Diabetes_Prevalance',
       'Fluview_US_FLU_Hospitalization_Rate_Metabolic_Disorders',
       'BRFSS_Age_55_64_Diabetes_Rate', 'BRFSS_Age_65_plus_Diabetes_Rate',
       'BRFSS_Obesity BMI Prevalance',
       'Fluview_US_FLU_Hospitalization_Rate_Obesity',
       'BRFSS_Age_55_64_Obesity_Rate', 'BRFSS_Age_65_plus_Obesity_Rate',
       'BRFSS_Kidney_Disease_Prevalance',
       'Fluview_US_FLU_Hospitalization_Rate_Kidney_Disease',
       'BRFSS_Age_55_64_Kidney_Disease_Rate',
       'BRFSS_Age_65_plus__Kidney_Disease_Rate',
       'BRFSS_Other_Cancer_Prevalance', 'BRFSS_55_64_Other_Cancer_Rate',
       'BRFSS_65_plus_Other_Cancer_Rate',
       'Census_Total_Population_Over_16_Estimate',
       'Census_Total_Workers_Over_16_Estimate',
       'COMMUTE_Census_Worker_Drive_To_Work_Rate',
       'COMMUTE_Census_Worker_Carpool_To_Work_Rate',
       'COMMUTE_Census_Worker_Public_Transportation_Rate',
       'COMMUTE_Census_Worker_Walk_Rate',
       'COMMUTE_Census_Worker_Taxicab_Motorcycle_Bicycle_Other_Rate',
       'COMMUTE_Census_Work_At_Home_Rate'],
      dtype='object')

In [22]:
X = pd.DataFrame(df, columns=["BRFSS_Asthma_Prevalance","BRFSS_COPD_Prevalance","BRFSS_Heart_Disease_Prevalance","BRFSS_2017_High_Cholestoral_Prevalance",
                            "High_Blood_Pressure_Prevalance", "BRFSS_Diabetes_Prevalance","BRFSS_Obesity BMI Prevalance","BRFSS_Kidney_Disease_Prevalance","BRFSS_Other_Cancer_Prevalance"])
X

,BRFSS_Asthma_Prevalance,BRFSS_COPD_Prevalance,BRFSS_Heart_Disease_Prevalance,BRFSS_2017_High_Cholestoral_Prevalance,High_Blood_Pressure_Prevalance,BRFSS_Diabetes_Prevalance,BRFSS_Obesity BMI Prevalance,BRFSS_Kidney_Disease_Prevalance,BRFSS_Other_Cancer_Prevalance
0,0.105,0.103,0.061,0.372,NaN,0.145,0.362,0.040,0.081
1,0.092,0.059,0.031,0.313,NaN,0.088,0.295,0.025,0.062
2,0.100,0.071,0.043,0.334,NaN,0.108,0.295,0.036,0.076
3,0.098,0.098,0.064,0.368,NaN,0.139,0.371,0.037,0.087
4,0.085,0.046,0.032,0.308,NaN,0.104,0.258,0.029,0.058
5,0.091,0.044,0.027,0.303,NaN,0.070,0.230,0.022,0.064
6,0.103,0.053,0.037,0.323,NaN,0.097,0.274,0.026,0.075
7,0.101,0.070,0.043,0.346,NaN,0.119,0.335,0.037,0.075
8,0.116,0.053,0.025,0.279,NaN,0.084,0.247,0.026,0.053
9,0.087,0.083,0.052,0.359,NaN,0.126,0.307,0.035,0.079
10,0.089,0.073,0.046,0.311,NaN,0.126,0.325,0.032,0.062
11,0.093,0.041,0.031,0.318,NaN,0.115,0.249,0.029,0.059
12,0.087,0.057,0.037,0.308,NaN,0.102,0.284,0.031,0.076
13,0.087,0.066,0.034,0.325,NaN,0.100,0.318,0.028,0.069
14,0.100,0.090,0.050,0.341,NaN,0.125,0.341,0.034,0.073
15,0.079,0.058,0.044,0.341,NaN,0.100,0.353,0.024,0.071
16,0.098,0.067,0.044,0.341,NaN,0.116,0.344,0.027,0.071
17,0.115,0.121,0.063,0.381,NaN,0.137,0.366,0.042,0.081
18,0.089,0.099,0.060,0.376,NaN,0.141,0.368,0.038,0.068
19,0.123,0.081,0.052,0.374,NaN,0.106,0.304,0.030,0.084
20,0.093,0.057,0.041,0.325,NaN,0.120,0.309,0.031,0.070
21,0.102,0.051,0.035,0.325,NaN,0.086,0.257,0.030,0.068
22,0.112,0.086,0.050,0.351,NaN,0.117,0.330,0.035,0.077
23,0.083,0.044,0.034,0.290,NaN,0.089,0.301,0.024,0.064
24,0.097,0.097,0.053,0.377,NaN,0.144,0.395,0.025,0.071
25,0.094,0.091,0.051,0.343,NaN,0.115,0.350,0.025,0.073
26,0.100,0.060,0.042,0.289,NaN,0.094,0.269,0.020,0.079
27,0.089,0.063,0.038,0.319,NaN,0.097,0.341,0.027,0.071
28,0.080,0.073,0.043,0.331,NaN,0.108,0.295,0.040,0.064
29,0.118,0.080,0.038,0.329,NaN,0.103,0.296,0.025,0.079
30,0.084,0.056,0.037,0.346,NaN,0.108,0.257,0.031,0.071
31,0.099,0.063,0.034,0.314,NaN,0.125,0.323,0.030,0.064
32,0.101,0.058,0.038,0.326,NaN,0.110,0.276,0.027,0.068
33,0.094,0.081,0.057,0.355,NaN,0.125,0.330,0.032,0.070
34,0.082,0.051,0.043,0.311,NaN,0.094,0.351,0.025,0.067
35,0.095,0.085,0.050,0.334,NaN,0.122,0.340,0.029,0.072
36,0.103,0.085,0.058,0.370,NaN,0.125,0.348,0.029,0.072
37,0.116,0.069,0.050,0.321,NaN,0.110,0.299,0.029,0.079
38,0.100,0.071,0.049,0.330,NaN,0.113,0.309,0.032,0.073
39,0.119,0.069,0.039,0.330,NaN,0.109,0.277,0.024,0.073
40,0.091,0.082,0.049,0.367,NaN,0.133,0.343,0.032,0.076
41,0.079,0.046,0.044,0.295,NaN,0.093,0.301,0.027,0.079
42,0.098,0.106,0.057,0.365,NaN,0.138,0.344,0.039,0.076
43,0.074,0.062,0.038,0.330,NaN,0.126,0.348,0.037,0.051
44,0.093,0.042,0.024,0.286,NaN,0.084,0.278,0.026,0.061
45,0.120,0.062,0.036,0.304,NaN,0.092,0.275,0.020,0.075
46,0.085,0.064,0.038,0.347,NaN,0.105,0.304,0.030,0.069
47,0.096,0.051,0.038,0.318,NaN,0.099,0.287,0.027,0.071
48,0.123,0.153,0.083,0.397,NaN,0.162,0.395,0.046,0.080
49,0.090,0.053,0.038,0.345,NaN,0.087,0.320,0.028,0.078
50,0.087,0.064,0.037,0.308,NaN,0.088,0.290,0.024,0.070

In [26]:
row_names = df["REGION"]
row_names

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: REGION, dtype: object

In [23]:
X.shape

(51, 9)

In [24]:
X.columns

Index(['BRFSS_Asthma_Prevalance', 'BRFSS_COPD_Prevalance',
       'BRFSS_Heart_Disease_Prevalance',
       'BRFSS_2017_High_Cholestoral_Prevalance',
       'High_Blood_Pressure_Prevalance', 'BRFSS_Diabetes_Prevalance',
       'BRFSS_Obesity BMI Prevalance', 'BRFSS_Kidney_Disease_Prevalance',
       'BRFSS_Other_Cancer_Prevalance'],
      dtype='object')

In [25]:
y = df["Covid_Death"]
y

0       13
1        3
2       24
3        8
4      153
5       51
6       69
7       10
8        9
9       77
10     111
11       0
12       7
13      99
14      49
15       7
16       9
17      11
18     239
19       5
20      18
21      89
22     259
23      12
24      20
25      14
26       4
27       3
28      17
29       3
30     267
31       4
32    1550
33       8
34       3
35      55
36      23
37      18
38      63
39       8
40      22
41       1
42      23
43      41
44       5
45      13
46      27
47     195
48       1
49      16
50       0
Name: Covid_Death, dtype: int64